import {
  ShoppingCart, ShoppingBasket, ShoppingBag, Utensils, UtensilsCrossed, Coffee, Pizza, Sandwich,
  Hamburger, Beef, Drumstick, Salad, Soup, Egg, Croissant, Cake, Cookie, Candy, Popsicle,
  IceCreamCone, Apple, Carrot, Milk, Wine, Beer, Martini, CupSoda,
  Car, CarTaxiFront, Bus, TrainFront, Bike, Fuel, SquareParking, Plane, Luggage, Hotel, Ship, MapPin, Truck,
  House, Building2, Lightbulb, Zap, Droplet, Flame, Wifi, Sofa, Bed, Wrench, Hammer, Paintbrush, Sprout, Bath, Recycle,
  Tv, Smartphone, Laptop, Monitor, Tablet, Watch, Headphones, Gamepad2, Film, Clapperboard, Music, Ticket,
  PartyPopper, Trophy, Dice5, Guitar,
  Heart, HeartPulse, Pill, Stethoscope, Hospital, Syringe, Dumbbell, Brain, Sparkles, Scissors,
  Shirt, Footprints, Glasses, Gem,
  GraduationCap, BookOpen, School, Pencil,
  Briefcase, Wallet, CreditCard, Banknote, Coins, PiggyBank, Landmark, TrendingUp, ChartLine, Receipt,
  HandCoins, Bitcoin, Percent, Calculator, Store, Package,
  Gift, Shield, ShieldCheck, Umbrella, Repeat, RefreshCw, Cloud, Globe,
  Baby, PawPrint, Dog, Cat, Users, HandHeart, Church, Phone, Mail, Key, Tag, Star, Bell, Clock,
  CalendarDays, Cigarette, Bug, Tent, Mountain, Sun, Camera, Palette, Mic,
} from "lucide-react";

type IconComponent = typeof Tag;

/*
 * Íconos de línea para categorías, con palabras clave en español para el
 * buscador. La clave es el nombre que se guarda ("icon:ShoppingCart").
 */
export const CATEGORY_ICONS: Record<string, { Icon: IconComponent; tags: string }> = {
  ShoppingCart:    { Icon: ShoppingCart,    tags: "mercado supermercado compras carrito" },
  ShoppingBasket:  { Icon: ShoppingBasket,  tags: "canasta mercado compras" },
  ShoppingBag:     { Icon: ShoppingBag,     tags: "bolsa compras tienda" },
  Utensils:        { Icon: Utensils,        tags: "restaurante comida cubiertos almuerzo cena" },
  UtensilsCrossed: { Icon: UtensilsCrossed, tags: "restaurante comida" },
  Coffee:          { Icon: Coffee,          tags: "cafe cafeteria desayuno tinto" },
  Pizza:           { Icon: Pizza,           tags: "pizza comida rapida" },
  Sandwich:        { Icon: Sandwich,        tags: "sanduche comida" },
  Hamburger:       { Icon: Hamburger,       tags: "hamburguesa comida rapida" },
  Beef:            { Icon: Beef,            tags: "carne asado" },
  Drumstick:       { Icon: Drumstick,       tags: "pollo comida" },
  Salad:           { Icon: Salad,           tags: "ensalada saludable" },
  Soup:            { Icon: Soup,            tags: "sopa almuerzo" },
  Egg:             { Icon: Egg,             tags: "huevo desayuno" },
  Croissant:       { Icon: Croissant,       tags: "panaderia pan desayuno" },
  Cake:            { Icon: Cake,            tags: "pastel torta cumpleanos postre" },
  Cookie:          { Icon: Cookie,          tags: "galleta snack dulce" },
  Candy:           { Icon: Candy,           tags: "dulces snack golosinas" },
  Popsicle:        { Icon: Popsicle,        tags: "helado paleta" },
  IceCreamCone:    { Icon: IceCreamCone,    tags: "helado postre" },
  Apple:           { Icon: Apple,           tags: "fruta manzana saludable" },
  Carrot:          { Icon: Carrot,          tags: "verdura mercado" },
  Milk:            { Icon: Milk,            tags: "leche lacteos" },
  Wine:            { Icon: Wine,            tags: "vino licor" },
  Beer:            { Icon: Beer,            tags: "cerveza licor bar" },
  Martini:         { Icon: Martini,         tags: "coctel bar fiesta licor rumba" },
  CupSoda:         { Icon: CupSoda,         tags: "gaseosa bebida" },

  Car:             { Icon: Car,             tags: "carro auto vehiculo" },
  CarTaxiFront:    { Icon: CarTaxiFront,    tags: "taxi uber didi" },
  Bus:             { Icon: Bus,             tags: "bus transporte transmilenio" },
  TrainFront:      { Icon: TrainFront,      tags: "tren metro" },
  Bike:            { Icon: Bike,            tags: "bicicleta cicla" },
  Fuel:            { Icon: Fuel,            tags: "gasolina combustible tanqueo" },
  SquareParking:   { Icon: SquareParking,   tags: "parqueadero parking" },
  Plane:           { Icon: Plane,           tags: "avion viaje vuelo" },
  Luggage:         { Icon: Luggage,         tags: "maleta viaje equipaje" },
  Hotel:           { Icon: Hotel,           tags: "hotel hospedaje" },
  Ship:            { Icon: Ship,            tags: "barco crucero" },
  MapPin:          { Icon: MapPin,          tags: "lugar ubicacion paseo" },
  Truck:           { Icon: Truck,           tags: "envio mudanza domicilio" },

  House:           { Icon: House,           tags: "casa hogar vivienda arriendo" },
  Building2:       { Icon: Building2,       tags: "edificio apartamento administracion" },
  Lightbulb:       { Icon: Lightbulb,       tags: "luz energia servicios" },
  Zap:             { Icon: Zap,             tags: "electricidad energia luz" },
  Droplet:         { Icon: Droplet,         tags: "agua acueducto" },
  Flame:           { Icon: Flame,           tags: "gas" },
  Wifi:            { Icon: Wifi,            tags: "internet wifi" },
  Sofa:            { Icon: Sofa,            tags: "muebles hogar" },
  Bed:             { Icon: Bed,             tags: "cama hogar" },
  Wrench:          { Icon: Wrench,          tags: "arreglos mantenimiento taller" },
  Hammer:          { Icon: Hammer,          tags: "reparaciones herramientas" },
  Paintbrush:      { Icon: Paintbrush,      tags: "pintura" },
  Sprout:          { Icon: Sprout,          tags: "jardin plantas" },
  Bath:            { Icon: Bath,            tags: "bano aseo" },
  Recycle:         { Icon: Recycle,         tags: "reciclaje aseo" },

  Tv:              { Icon: Tv,              tags: "television streaming" },
  Smartphone:      { Icon: Smartphone,      tags: "celular telefono plan" },
  Laptop:          { Icon: Laptop,          tags: "computador portatil" },
  Monitor:         { Icon: Monitor,         tags: "pantalla computador" },
  Tablet:          { Icon: Tablet,          tags: "tablet ipad" },
  Watch:           { Icon: Watch,           tags: "reloj smartwatch" },
  Headphones:      { Icon: Headphones,      tags: "audifonos musica" },
  Gamepad2:        { Icon: Gamepad2,        tags: "videojuegos juegos consola" },
  Film:            { Icon: Film,            tags: "cine peliculas" },
  Clapperboard:    { Icon: Clapperboard,    tags: "peliculas series streaming" },
  Music:           { Icon: Music,           tags: "musica spotify" },
  Ticket:          { Icon: Ticket,          tags: "boletas eventos entradas concierto" },
  PartyPopper:     { Icon: PartyPopper,     tags: "fiesta salidas celebracion rumba" },
  Trophy:          { Icon: Trophy,          tags: "deporte premio" },
  Dice5:           { Icon: Dice5,           tags: "juegos azar apuestas" },
  Guitar:          { Icon: Guitar,          tags: "musica instrumento clases" },

  Heart:           { Icon: Heart,           tags: "salud amor pareja" },
  HeartPulse:      { Icon: HeartPulse,      tags: "salud medico" },
  Pill:            { Icon: Pill,            tags: "medicina farmacia pastillas drogueria" },
  Stethoscope:     { Icon: Stethoscope,     tags: "medico doctor consulta" },
  Hospital:        { Icon: Hospital,        tags: "hospital clinica" },
  Syringe:         { Icon: Syringe,         tags: "vacuna examenes" },
  Dumbbell:        { Icon: Dumbbell,        tags: "gym gimnasio ejercicio" },
  Brain:           { Icon: Brain,           tags: "psicologo mente terapia" },
  Sparkles:        { Icon: Sparkles,        tags: "belleza cuidado personal skincare" },
  Scissors:        { Icon: Scissors,        tags: "peluqueria barberia corte" },

  Shirt:           { Icon: Shirt,           tags: "ropa camisa" },
  Footprints:      { Icon: Footprints,      tags: "zapatos tenis" },
  Glasses:         { Icon: Glasses,         tags: "gafas lentes optica" },
  Gem:             { Icon: Gem,             tags: "joyas accesorios" },

  GraduationCap:   { Icon: GraduationCap,   tags: "educacion universidad estudio" },
  BookOpen:        { Icon: BookOpen,        tags: "libros lectura curso" },
  School:          { Icon: School,          tags: "colegio escuela" },
  Pencil:          { Icon: Pencil,          tags: "utiles papeleria" },

  Briefcase:       { Icon: Briefcase,       tags: "trabajo salario oficina" },
  Wallet:          { Icon: Wallet,          tags: "billetera dinero" },
  CreditCard:      { Icon: CreditCard,      tags: "tarjeta credito deuda" },
  Banknote:        { Icon: Banknote,        tags: "efectivo dinero billete" },
  Coins:           { Icon: Coins,           tags: "monedas dinero" },
  PiggyBank:       { Icon: PiggyBank,       tags: "ahorro alcancia" },
  Landmark:        { Icon: Landmark,        tags: "banco impuestos" },
  TrendingUp:      { Icon: TrendingUp,      tags: "inversiones rentabilidad" },
  ChartLine:       { Icon: ChartLine,       tags: "inversiones bolsa acciones" },
  Receipt:         { Icon: Receipt,         tags: "factura recibo cuentas" },
  HandCoins:       { Icon: HandCoins,       tags: "prestamo pago deuda" },
  Bitcoin:         { Icon: Bitcoin,         tags: "cripto bitcoin" },
  Percent:         { Icon: Percent,         tags: "intereses descuento" },
  Calculator:      { Icon: Calculator,      tags: "impuestos contabilidad" },
  Store:           { Icon: Store,           tags: "negocio tienda ventas" },
  Package:         { Icon: Package,         tags: "paquete ventas envio" },

  Gift:            { Icon: Gift,            tags: "regalo" },
  Shield:          { Icon: Shield,          tags: "seguro poliza proteccion" },
  ShieldCheck:     { Icon: ShieldCheck,     tags: "seguro poliza" },
  Umbrella:        { Icon: Umbrella,        tags: "seguro proteccion" },
  Repeat:          { Icon: Repeat,          tags: "suscripcion recurrente mensual" },
  RefreshCw:       { Icon: RefreshCw,       tags: "suscripcion renovacion" },
  Cloud:           { Icon: Cloud,           tags: "nube icloud almacenamiento" },
  Globe:           { Icon: Globe,           tags: "internet web dominio" },

  Baby:            { Icon: Baby,            tags: "bebe hijos ninos" },
  PawPrint:        { Icon: PawPrint,        tags: "mascota perro gato veterinaria" },
  Dog:             { Icon: Dog,             tags: "perro mascota" },
  Cat:             { Icon: Cat,             tags: "gato mascota" },
  Users:           { Icon: Users,           tags: "familia amigos" },
  HandHeart:       { Icon: HandHeart,       tags: "donacion caridad ayuda" },
  Church:          { Icon: Church,          tags: "iglesia diezmo" },
  Phone:           { Icon: Phone,           tags: "telefono llamadas" },
  Mail:            { Icon: Mail,            tags: "correo envios" },
  Key:             { Icon: Key,             tags: "llaves cerrajero" },
  Tag:             { Icon: Tag,             tags: "etiqueta general otros" },
  Star:            { Icon: Star,            tags: "favorito especial" },
  Bell:            { Icon: Bell,            tags: "alertas recordatorio" },
  Clock:           { Icon: Clock,           tags: "tiempo horas" },
  CalendarDays:    { Icon: CalendarDays,    tags: "calendario mensual" },
  Cigarette:       { Icon: Cigarette,       tags: "cigarrillo vape" },
  Bug:             { Icon: Bug,             tags: "hormiga gastos hormiga bicho" },
  Tent:            { Icon: Tent,            tags: "camping paseo" },
  Mountain:        { Icon: Mountain,        tags: "paseo naturaleza viaje" },
  Sun:             { Icon: Sun,             tags: "vacaciones playa" },
  Camera:          { Icon: Camera,          tags: "fotografia camara" },
  Palette:         { Icon: Palette,         tags: "arte diseno" },
  Mic:             { Icon: Mic,             tags: "podcast grabacion" },
};

/** Emojis frecuentes para categorías (también se puede pegar cualquier otro). */
export const CATEGORY_EMOJIS = [
  "🛒", "🍔", "🍕", "☕", "🥗", "🍎", "🧁", "🍺", "🍷", "🍿",
  "🚗", "🚕", "🚌", "⛽", "🅿️", "✈️", "🚲", "🛵", "🧳", "🗺️",
  "🏠", "💡", "💧", "🔥", "📡", "🛋️", "🧹", "🔧", "🪴", "🧺",
  "📱", "💻", "🎮", "📺", "🎬", "🎵", "🎟️", "🎉", "📷", "🎨",
  "❤️", "💊", "🏥", "💪", "🧠", "💅", "💇", "🧴", "🦷", "👓",
  "👕", "👟", "👜", "💍", "📚", "🎓", "✏️", "🏫", "💼", "🧾",
  "💰", "💳", "💵", "🐷", "📈", "🏦", "🎁", "🛡️", "🔄", "☁️",
  "👶", "🐶", "🐱", "👨‍👩‍👧", "🙏", "🐜", "🍪", "⭐", "🏷️", "⚪",
];

/** Paleta de colores para categorías. */
export const CATEGORY_COLORS = [
  "#DC2626", "#EA580C", "#D97706", "#CA8A04", "#84CC16",
  "#65A30D", "#16A34A", "#059669", "#0D9488", "#0891B2",
  "#0284C7", "#2563EB", "#4F46E5", "#7C3AED", "#9333EA",
  "#C026D3", "#DB2777", "#E11D48", "#F43F5E", "#FB7185",
  "#64748B", "#78716C", "#57534E", "#44403C", "#292524",
  "#991B1B", "#7C2D12", "#92400E", "#B45309", "#A16207",
];
